In [5]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [6]:
data_dir = 'data'
af = 'u'

window_width = 7200 #10800 #120 #60 #600 # 120  # seconds
window_stride = 3600 #10800 #60 #30 #600 # 60  # seconds

start_idx = 0
end_idx = 12000 #6000

pf = f'{window_width}-{window_stride}.__2__'

df__train = pd.read_csv(f'{data_dir}/tr.{af}4.{window_width}-{window_stride}.w-{start_idx}-{end_idx}.csv', index_col=[0])
df__test = pd.read_csv(f'{data_dir}/t.{af}4.{window_width}-{window_stride}.w-{start_idx}-{end_idx}.csv', index_col=[0])

In [7]:
# print(len(df__train), len(df__test))
# df__train = df__train.loc[df__train['n_flows'] > 1]
# df__test = df__test.loc[df__test['n_flows'] > 1]
print(len(df__train), len(df__test))

1682205 45701

In [11]:
df__train['Label'].value_counts()

flow=Background-UDP-Established             1238478
flow=Background-TCP-Established              161639
flow=Background-TCP-Attempt                   78208
flow=Background-UDP-Attempt                   67514
flow=From-Botnet-V44-TCP-Attempt              52384
flow=Background                               50329
flow=Background-UDP-NTP-Established-1         10689
flow=To-Background-UDP-CVUT-DNS-Server         4489
flow=Background-Attempt-cmpgw-CVUT             4209
flow=To-Background-CVUT-WebServer              2943
flow=To-Background-CVUT-Proxy                  1342
flow=Background-Established-cmpgw-CVUT         1247
flow=From-Botnet-V44-TCP-Established            981
flow=From-Normal-V44-Stribrek                   840
flow=From-Normal-V44-Grill                      577
flow=To-Background-Grill                        497
flow=To-Background-MatLab-Server                472
flow=To-Normal-V44-UDP-NTP-server               360
flow=Background-google-analytics14              258
flow=Background-google-analytics8               241
flow=Background-google-analytics3               237
flow=Background-google-analytics2               235
flow=Background-google-analytics16              234
flow=Background-google-analytics6               232
flow=Background-google-analytics11              232
flow=Background-google-analytics12              230
flow=Background-google-analytics15              226
flow=Background-google-analytics13              226
flow=From-Normal-V44-Jist                       224
flow=Background-google-analytics5               221
flow=Background-google-analytics1               219
flow=Background-google-analytics4               218
flow=Background-google-analytics10              214
flow=Background-google-analytics7               213
flow=Background-google-analytics9               205
flow=From-Background-CVUT-Proxy                 199
flow=From-Normal-V44-CVUT-WebServer             190
flow=Background-google-webmail                  181
flow=To-Background-Stribrek                     161
flow=Background-google-pop                      110
flow=To-Background-Jist                          99
flow=Background-www.fel.cvut.cz                  60
flow=From-Normal-V44-MatLab-Server               52
flow=Background-ajax.google                      34
flow=From-Botnet-V44-ICMP                        28
flow=Normal-V44-HTTP-windowsupdate               16
flow=From-Normal-V44-UDP-CVUT-DNS-Server          6
flow=From-Botnet-V44-TCP-WEB-Established          2
flow=From-Botnet-V44-UDP-DNS                      2
flow=From-Botnet-V44-UDP-Attempt                  2
Name: Label, dtype: int64

In [6]:
# df__test.loc[(df__test['Label'] == 5) & (df__test['n_flows'] > 1)]

In [34]:
df__test.columns

Index(['Conversation', 'SrcAddr', 'DstAddr', 'n_flows', 'StreamID_unique',
       'Sport_nunique', 'Sport_mean', 'Sport_std', 'Sport_max', 'Sport_median',
       'Sport_RU', 'Dport_nunique', 'Dport_mean', 'Dport_std', 'Dport_max',
       'Dport_median', 'Dport_RU', 'sTos_nunique', 'sTos_mean', 'sTos_std',
       'sTos_max', 'sTos_median', 'sTos_RU', 'dTos_nunique', 'dTos_mean',
       'dTos_std', 'dTos_max', 'dTos_median', 'dTos_RU', 'Dir_nunique',
       'Dir_RU', 'State_orig_nunique', 'State_orig_RU', 'State_nunique',
       'State_RU', 'Dur_sum', 'Dur_mean', 'Dur_std', 'Dur_max', 'Dur_median',
       'Dur_RU', 'TotBytes_sum', 'TotBytes_mean', 'TotBytes_std',
       'TotBytes_max', 'TotBytes_median', 'TotBytes_RU', 'SrcBytes_sum',
       'SrcBytes_mean', 'SrcBytes_std', 'SrcBytes_max', 'SrcBytes_median',
       'SrcBytes_RU', 'DstBytes_sum', 'DstBytes_mean', 'DstBytes_std',
       'DstBytes_max', 'DstBytes_median', 'DstBytes_RU', 'TotPkts_sum',
       'TotPkts_mean', 'TotPkts_std', 'TotPkts_max', 'TotPkts_median',
       'TotPkts_RU', 'PktsPerSec_mean', 'PktsPerSec_std', 'PktsPerSec_max',
       'PktsPerSec_median', 'PktsPerSec_RU', 'BytesPerSec_mean',
       'BytesPerSec_std', 'BytesPerSec_max', 'BytesPerSec_median',
       'BytesPerSec_RU', 'SrcBytesPerSec_mean', 'SrcBytesPerSec_std',
       'SrcBytesPerSec_max', 'SrcBytesPerSec_median', 'SrcBytesPerSec_RU',
       'DstBytesPerSec_mean', 'DstBytesPerSec_std', 'DstBytesPerSec_max',
       'DstBytesPerSec_median', 'DstBytesPerSec_RU', 'BytesPerPkt_mean',
       'BytesPerPkt_std', 'BytesPerPkt_max', 'BytesPerPkt_median',
       'BytesPerPkt_RU', 'Label', 'window_id'],
      dtype='object')

# Bot

In [35]:
dfb__test = df__test.loc[df__test['Label'] == 5]
dfb__test

,Conversation,SrcAddr,DstAddr,n_flows,StreamID_unique,Sport_nunique,Sport_mean,Sport_std,Sport_max,Sport_median,...,DstBytesPerSec_max,DstBytesPerSec_median,DstBytesPerSec_RU,BytesPerPkt_mean,BytesPerPkt_std,BytesPerPkt_max,BytesPerPkt_median,BytesPerPkt_RU,Label,window_id
3431,41.232.73.23 -> 150.35.87.168,41.232.73.23,150.35.87.168,4,[ 51591 84191 101058 109906],3,6667.0,0.816497,6668,6667.0,...,2.852762,0.609414,1.0,77.096928,7.618773,88.506849,73.570062,1.0,5,11999

In [36]:
dfb__train = df__train.loc[df__train['Label'] == 5]
dfb__train

,Conversation,SrcAddr,DstAddr,n_flows,StreamID_unique,Sport_nunique,Sport_mean,Sport_std,Sport_max,Sport_median,...,DstBytesPerSec_max,DstBytesPerSec_median,DstBytesPerSec_RU,BytesPerPkt_mean,BytesPerPkt_std,BytesPerPkt_max,BytesPerPkt_median,BytesPerPkt_RU,Label,window_id
7982,150.35.87.168 -> 211.103.44.3,150.35.87.168,211.103.44.3,2,[1504715 1511986],2,2360.5,180.312229,2488,2360.5,...,139.062321,69.641693,1.0,61.583333,0.589256,62.000000,61.583333,1.0,5,11999
7993,150.35.87.168 -> 211.103.44.4,150.35.87.168,211.103.44.4,2,[1504733 1512008],2,2360.0,178.190909,2486,2360.0,...,136.865022,136.787161,1.0,73.200000,0.000000,73.200000,73.200000,-0.0,5,11999
8235,150.35.87.168 -> 211.103.45.3,150.35.87.168,211.103.45.3,2,[1512039 1518861],2,2614.5,178.898016,2741,2614.5,...,932.666660,466.333330,1.0,65.750000,5.303301,69.500000,65.750000,1.0,5,11999
8246,150.35.87.168 -> 211.103.45.4,150.35.87.168,211.103.45.4,2,[1512043 1518864],2,2617.5,180.312229,2745,2617.5,...,1034.378208,517.189104,1.0,61.944444,0.392837,62.222222,61.944444,1.0,5,11999
8488,150.35.87.168 -> 211.103.46.3,150.35.87.168,211.103.46.3,2,[1518865 1526255],2,2872.0,181.019336,3000,2872.0,...,0.000000,0.000000,-0.0,92.500000,0.000000,92.500000,92.500000,-0.0,5,11999
8499,150.35.87.168 -> 211.103.46.4,150.35.87.168,211.103.46.4,2,[1518873 1526256],2,2871.0,179.605122,2998,2871.0,...,142.380250,71.190125,1.0,67.066667,8.108158,72.800000,67.066667,1.0,5,11999
8741,150.35.87.168 -> 211.103.47.3,150.35.87.168,211.103.47.3,2,[1526262 1535075],2,2131.0,1230.365799,3001,2131.0,...,133.376770,66.688385,1.0,61.250000,1.060660,62.000000,61.250000,1.0,5,11999
8752,150.35.87.168 -> 211.103.47.4,150.35.87.168,211.103.47.4,2,[1526278 1535104],2,2133.5,1226.830265,3001,2133.5,...,140.782603,125.563269,1.0,72.700000,0.707107,73.200000,72.700000,1.0,5,11999
8994,150.35.87.168 -> 211.103.48.3,150.35.87.168,211.103.48.3,2,[1535125 1542068],2,1395.5,178.898016,1522,1395.5,...,0.111086,0.055543,1.0,77.250000,21.566757,92.500000,77.250000,1.0,5,11999
9005,150.35.87.168 -> 211.103.48.4,150.35.87.168,211.103.48.4,2,[1535171 1542085],2,1394.0,178.190909,1520,1394.0,...,134.897414,67.448707,1.0,77.250000,22.980970,93.500000,77.250000,1.0,5,11999
9247,150.35.87.168 -> 211.103.49.3,150.35.87.168,211.103.49.3,2,[1542088 1549542],2,1649.0,179.605122,1776,1649.0,...,0.226431,0.113215,1.0,77.833333,22.863119,94.000000,77.833333,1.0,5,11999
9258,150.35.87.168 -> 211.103.49.4,150.35.87.168,211.103.49.4,2,[1542200 1549553],2,1651.5,177.483802,1777,1651.5,...,122.610593,61.305296,1.0,67.433333,8.155298,73.200000,67.433333,1.0,5,11999
9500,150.35.87.168 -> 211.103.50.3,150.35.87.168,211.103.50.3,2,[1549566 1558289],2,1905.0,176.776695,2030,1905.0,...,244.964474,122.482237,1.0,76.800000,21.496046,92.000000,76.800000,1.0,5,11999
9511,150.35.87.168 -> 211.103.50.4,150.35.87.168,211.103.50.4,2,[1549666 1558295],2,1905.5,177.483802,2031,1905.5,...,235.900843,185.651787,1.0,64.805556,5.146166,68.444444,64.805556,1.0,5,11999

In [39]:
print(dfb__test['BytesPerPkt_mean'].describe(), '\n')
print(dfb__train['BytesPerPkt_mean'].describe())

count     1.000000
mean     77.096928
std            NaN
min      77.096928
25%      77.096928
50%      77.096928
75%      77.096928
max      77.096928
Name: BytesPerPkt_mean, dtype: float64

count    14.000000
mean     71.240476
std       8.715569
min      61.250000
25%      65.041667
50%      70.066667
75%      77.137500
max      92.500000
Name: BytesPerPkt_mean, dtype: float64

0.0

# Normal

In [40]:
dfnm__test = df__test.loc[df__test['Label'] != 5]
dfnm__test

,Conversation,SrcAddr,DstAddr,n_flows,StreamID_unique,Sport_nunique,Sport_mean,Sport_std,Sport_max,Sport_median,...,DstBytesPerSec_max,DstBytesPerSec_median,DstBytesPerSec_RU,BytesPerPkt_mean,BytesPerPkt_std,BytesPerPkt_max,BytesPerPkt_median,BytesPerPkt_RU,Label,window_id
0,112.68.196.144 -> 150.35.88.126,112.68.196.144,150.35.88.126,3,[53830 59196 70068],3,20356.000000,32450.852500,57822,2154.0,...,0.000000e+00,0.000000,-0.000000,77.791667,27.351969,109.375000,62.000000,0.579380,0,11999
1,150.35.87.141 -> 150.35.83.12,150.35.87.141,150.35.83.12,16017,[ 51592 51593 51594 ... 109904 109905 109907],12239,46950.733408,8124.272705,61001,46949.0,...,3.277864e+07,562167.216890,1.000000,162.219486,55.152700,362.000000,205.000000,0.261092,1,11999
2,150.35.87.141 -> 150.35.83.16,150.35.87.141,150.35.83.16,3,[ 82328 98791 109002],1,771.000000,0.000000,771,771.0,...,2.331760e-01,0.186508,1.000000,521.541316,12.491941,529.431777,528.053333,1.000000,1,11999
3,150.35.87.141 -> 172.232.73.98,150.35.87.141,172.232.73.98,11,[ 59458 70771 77949 85055 91694 95204 98...,11,47220.000000,8011.810307,58402,47628.0,...,4.947544e+02,486.402988,1.000000,154.590909,41.810775,180.000000,179.000000,0.684657,0,11999
4,150.35.87.141 -> 177.146.253.26,150.35.87.141,177.146.253.26,2,[93590 93593],2,58411.500000,603.162084,58838,58411.5,...,4.160514e+02,212.335617,1.000000,128.500000,4.949747,132.000000,128.500000,1.000000,0,11999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3424,150.35.90.4 -> 150.35.90.6,150.35.90.4,150.35.90.6,18,[ 52476 55866 57143 57396 59707 76580 78...,1,261.000000,0.000000,261,261.0,...,6.669040e-03,0.000285,0.680250,73.771787,21.246004,104.500000,72.200000,1.000000,0,11999
3425,150.35.90.4 -> 150.35.90.60,150.35.90.4,150.35.90.60,2,[59957 89267],1,0.000000,0.000000,0,0.0,...,0.000000e+00,0.000000,-0.000000,37.125000,52.502679,74.250000,37.125000,1.000000,0,11999
3428,150.35.90.4 -> 150.35.90.7,150.35.90.4,150.35.90.7,24,[ 54248 55958 57402 60140 61480 61782 76...,1,261.000000,0.000000,261,261.0,...,2.376920e-03,0.000000,0.368526,67.193965,21.541108,93.000000,69.975000,0.920438,0,11999
3429,150.35.90.4 -> 150.35.90.8,150.35.90.4,150.35.90.8,17,[ 52485 53635 54936 72053 74202 76276 83...,1,261.000000,0.000000,261,261.0,...,4.423939e-03,0.000000,0.589429,61.223187,29.674465,85.000000,70.461538,0.931571,0,11999
3430,150.35.90.4 -> 150.35.90.9,150.35.90.4,150.35.90.9,3,[ 57416 91498 105092],1,0.000000,0.000000,0,0.0,...,5.283789e-03,0.001560,1.000000,61.153439,2.378641,63.888889,60.000000,1.000000,0,11999

In [41]:
dfnm__train = df__train.loc[df__train['Label'] != 5]
dfnm__train

,Conversation,SrcAddr,DstAddr,n_flows,StreamID_unique,Sport_nunique,Sport_mean,Sport_std,Sport_max,Sport_median,...,DstBytesPerSec_max,DstBytesPerSec_median,DstBytesPerSec_RU,BytesPerPkt_mean,BytesPerPkt_std,BytesPerPkt_max,BytesPerPkt_median,BytesPerPkt_RU,Label,window_id
37,100.120.31.18 -> 150.35.87.232,100.120.31.18,150.35.87.232,2,[1549741 1567601],2,25712.50,2182.838634,27256,25712.5,...,2.473707e+05,189580.132500,1.0,121.500,75.660426,175.0,121.500,1.0,0,11999
56,100.169.107.209 -> 150.35.87.232,100.169.107.209,150.35.87.232,2,[1553345 1553535],1,43095.00,0.000000,43095,43095.0,...,2.832075e+05,252471.768329,1.0,183.500,81.317280,241.0,183.500,1.0,0,11999
61,100.78.156.111 -> 150.35.87.232,100.78.156.111,150.35.87.232,2,[1499534 1506027],2,43578.00,1.414214,43579,43578.0,...,4.172113e+05,319420.188833,1.0,221.500,132.228968,315.0,221.500,1.0,0,11999
63,100.79.79.94 -> 150.35.87.232,100.79.79.94,150.35.87.232,2,[1478813 1517282],2,42832.50,17592.109609,55272,42832.5,...,4.171618e-02,0.041509,1.0,70.250,0.353553,70.5,70.250,1.0,0,11999
95,100.92.50.118 -> 150.35.87.232,100.92.50.118,150.35.87.232,2,[1480041 1567452],1,36209.00,0.000000,36209,36209.0,...,1.189285e+06,594642.929106,1.0,446.625,209.833937,595.0,446.625,1.0,0,11999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66618,99.47.188.102 -> 150.35.90.61,99.47.188.102,150.35.90.61,2,[1449133 1561788],1,80.00,0.000000,80,80.0,...,0.000000e+00,0.000000,-0.0,89.500,0.000000,89.5,89.500,-0.0,0,11999
66633,99.5.99.236 -> 150.35.87.232,99.5.99.236,150.35.87.232,2,[1456455 1510475],2,37061.00,22816.921615,53195,37061.0,...,1.674018e+05,161746.663232,1.0,67.000,4.242641,70.0,67.000,1.0,0,11999
66655,99.53.179.232 -> 150.35.87.232,99.53.179.232,150.35.87.232,2,[1480097 1550109],2,42434.50,33.234019,42458,42434.5,...,1.695567e+05,144731.692849,1.0,100.250,47.729708,134.0,100.250,1.0,0,11999
66678,99.63.167.205 -> 150.35.87.232,99.63.167.205,150.35.87.232,4,[1442651 1451056 1465513 1481034],4,40257.75,1240.543530,41640,40222.0,...,1.389864e+05,56719.436856,1.0,251.000,32.215421,296.5,243.500,1.0,0,11999
66679,99.63.183.35 -> 150.35.87.232,99.63.183.35,150.35.87.232,2,[1446884 1557580],2,1148.00,1.414214,1149,1148.0,...,1.955159e+05,97757.976941,1.0,99.000,46.669048,132.0,99.000,1.0,0,11999

In [42]:
print(dfnm__test['BytesPerPkt_mean'].describe(), '\n')
print(dfnm__train['BytesPerPkt_mean'].describe())

count    1576.000000
mean      245.412172
std       174.940795
min        29.666667
25%       103.809823
50%       189.406085
75%       343.200275
max      1254.140860
Name: BytesPerPkt_mean, dtype: float64

count    7224.000000
mean      170.944536
std       144.054759
min         0.000000
25%        82.620590
50%       113.688784
75%       198.604167
max      1315.881818
Name: BytesPerPkt_mean, dtype: float64

# Ft describe ?

In [46]:
print(dfb__test['BytesPerPkt_RU'].describe(), '\n')
print(dfb__train['BytesPerPkt_RU'].describe())

count    1.0
mean     1.0
std      NaN
min      1.0
25%      1.0
50%      1.0
75%      1.0
max      1.0
Name: BytesPerPkt_RU, dtype: float64

count    14.000000
mean      0.857143
std       0.363137
min      -0.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       1.000000
Name: BytesPerPkt_RU, dtype: float64

In [47]:
print(dfnm__test['BytesPerPkt_RU'].describe(), '\n')
print(dfnm__train['BytesPerPkt_RU'].describe())

count    1576.000000
mean        0.967164
std         0.135277
min        -0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: BytesPerPkt_RU, dtype: float64

count    7224.000000
mean        0.933811
std         0.220010
min        -0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: BytesPerPkt_RU, dtype: float64

# Compare features

In [26]:
# fts = ['DstAddr_RU','Sport_std','Dport_std','BytesPerPkt_RU','PktsPerSec_std','BytesPerSec_std','SrcBytesPerSec_std','DstBytesPerSec_std']
fts = ['n_flows','DstAddr_RU','Sport_std','Dport_std','BytesPerPkt_std','PktsPerSec_std','BytesPerSec_std','SrcBytesPerSec_std','DstBytesPerSec_std',
'sTos_std','dTos_std']

fts = ['n_flows','DstAddr_RU','Sport_max','Dport_max','BytesPerPkt_mean','PktsPerSec_mean','BytesPerSec_mean','SrcBytesPerSec_mean','DstBytesPerSec_mean','sTos_std','dTos_std']

fts = ['SrcAddr'] + ['n_flows','State_nunique','State_RU','State_orig_nunique','State_orig_RU','Sport_RU','Dport_RU']

In [27]:
dfb__test[fts]

,SrcAddr,n_flows,State_nunique,State_RU,State_orig_nunique,State_orig_RU,Sport_RU,Dport_RU
5,41.232.73.23,2,1,-0.0,1,-0.0,1.0,-0.0
4,41.232.73.23,2,1,-0.0,1,-0.0,1.0,-0.0
4,41.232.73.23,2,1,-0.0,1,-0.0,1.0,-0.0
4,41.232.73.23,1,1,1.0,1,1.0,1.0,1.0

In [28]:
dfb__train[fts]

,SrcAddr,n_flows,State_nunique,State_RU,State_orig_nunique,State_orig_RU,Sport_RU,Dport_RU
7241,150.35.87.168,2149,3,0.085707,9,0.127089,0.932542,0.001052
2957,150.35.87.168,1546,2,0.087315,8,0.126004,0.931541,0.000735

In [29]:
dfnm__test[fts]

,SrcAddr,n_flows,State_nunique,State_RU,State_orig_nunique,State_orig_RU,Sport_RU,Dport_RU
0,112.68.196.144,3,2,0.579380,2,0.579380,1.000000,1.000000
1,150.35.87.141,12081,3,0.000342,4,0.000354,0.971527,0.002096
2,150.35.87.174,3286,5,0.124639,16,0.149327,0.982534,0.696489
3,150.35.87.62,32906,9,0.078305,66,0.142981,0.902949,0.175809
4,150.35.90.4,201,3,0.100197,3,0.100197,0.084199,0.364196
0,150.35.87.141,8575,3,0.000482,4,0.000500,0.977521,0.002997
1,150.35.87.174,3218,5,0.127744,17,0.153432,0.979275,0.685525
2,150.35.87.62,13495,9,0.088546,49,0.155891,0.918201,0.200812
3,150.35.90.4,200,3,0.075750,3,0.075750,0.069253,0.365531
0,150.35.87.141,3985,2,0.000281,2,0.000281,0.986886,0.003437
1,150.35.87.174,2007,4,0.124714,15,0.149126,0.989351,0.740556
2,150.35.87.62,3525,9,0.101923,33,0.182780,0.949398,0.181540
3,150.35.90.4,129,3,0.086755,3,0.086755,0.077139,0.395802
0,150.35.87.141,277,1,-0.000000,1,-0.000000,0.994661,0.010630
1,150.35.87.174,328,3,0.090593,7,0.099368,1.000000,0.916653
2,150.35.87.62,30,2,0.197875,3,0.250863,0.972827,0.282723
3,150.35.90.4,21,1,-0.000000,1,-0.000000,-0.000000,0.503739

In [30]:
dfnm__train[fts]

,SrcAddr,n_flows,State_nunique,State_RU,State_orig_nunique,State_orig_RU,Sport_RU,Dport_RU
0,100.100.162.243,1,1,1.0,1,1.0,1.0,1.0
1,100.100.184.43,1,1,1.0,1,1.0,1.0,1.0
2,100.100.231.46,1,1,1.0,1,1.0,1.0,1.0
3,100.100.26.156,1,1,1.0,1,1.0,1.0,1.0
4,100.100.40.53,1,1,1.0,1,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...
19684,99.58.32.214,1,1,1.0,1,1.0,1.0,1.0
19685,99.63.183.35,1,1,1.0,1,1.0,1.0,1.0
19686,99.64.183.124,1,1,1.0,1,1.0,1.0,1.0
19687,99.66.151.35,1,1,1.0,1,1.0,1.0,1.0
19688,99.66.245.160,1,1,1.0,1,1.0,1.0,1.0